### ISSUE TITLE
Minifying App Stylesheet Error

### ISSUE THREAD

**Issue by steltz** [juliancwirko/meteor-npm-foundation-test#2]
Hi Julian! Thank you for putting this together. I saw your posts in other thread about getting meteor/foundation set-up. I'd like to use Meteor with Foundation but I'm having trouble debugging this error:

```
While minifying app stylesheet:
 /tools/isobuild/bundler.js:1546:22: Object [object Object] has no method 'split'
  at /tools/isobuild/bundler.js:1546:22
  at /Users/steltz/.meteor/packages/meteor-       tool/.1.3.2_4.1t37v8t++os.osx.x86_64+web.browser+web.cordova/mt-   os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:209:40
  at _.each._.forEach (/Users/steltz/.meteor/packages/meteor-  tool/.1.3.2_4.1t37v8t++os.osx.x86_64+web.browser+web.cordova/mt-   os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
  at Function._.some._.any (/Users/steltz/.meteor/packages/meteor-  tool/.1.3.2_4.1t37v8t++os.osx.x86_64+web.browser+web.cordova/mt-  os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:208:5)
  at Object._.extend.Npm.require (/tools/isobuild/bundler.js:1537:15)
  at Object.require (/tools/isobuild/bundler.js:1534:11)
  at getPostCSSParser (packages/minifier-postcss/plugin/minify-css.js:58:22)
  at packages/minifier-postcss/plugin/minify-css.js:152:25
  at Array.map (native)
  at mergeCss (packages/minifier-postcss/plugin/minify-css.js:133:23)
  at CssToolsMinifier.processFilesForBundle (packages/minifier-postcss/plugin/minify-css.js:103:18)
```

Can you point me in the right direction to debug this error? Thanks again!

**Comment by juliancwirko** [comment]
Hi, it looks like a bug from postCSS package. Do you use PostCSS package and Foundation from Npm? Could you prepare small reproduction repository? The repo works well as is.

**Comment by steltz** [comment]
Thanks for the quick response! I got it working :) I just `npm install --save-dev autoprefixer` then restarted my Meteor app. I'm new to Meteor/Node, so I'm feeling my way around.

Thanks again for putting this together, it would've taken me a long time to figure this out.
